name: Compile and Deploy PDF
on:
  push:
    branches:
      - main
jobs:
  compile_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Copy
        run: |
          mkdir out
          cp ./main.pdf ./out/main.pdf
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: UofTS24Notes
          path: out/main.pdf
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          branch: gh-pages
          folder: out
          single_commit: true
          clean: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
